(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.MazeLevels = factory();
})(globalThis, function () {
  return [
    {
      id: "maze-01",
      map: ["#####", "#S#G#", "# # #", "#   #", "#####"],
      solution: ["down", "down", "right", "right", "up", "up"],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-02",
      map: ["#####", "#S# #", "# #G#", "#   #", "#####"],
      solution: ["down", "down", "right", "right", "up"],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-03",
      map: ["#####", "#S  #", "### #", "#  G#", "#####"],
      solution: ["right", "right", "down", "down"],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-04",
      map: ["#####", "#S  #", "### #", "#G  #", "#####"],
      solution: ["right", "right", "down", "down", "left", "left"],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-05",
      map: ["#####", "#S# #", "#G# #", "#   #", "#####"],
      solution: ["down"],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-06",
      map: ["#####", "#S# #", "# # #", "#  G#", "#####"],
      solution: ["down", "down", "right", "right"],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-07",
      map: [
        "#######",
        "#S  #G#",
        "### # #",
        "#   # #",
        "# ### #",
        "#     #",
        "#######",
      ],
      solution: [
        "right",
        "right",
        "down",
        "down",
        "left",
        "left",
        "down",
        "down",
        "right",
        "right",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-08",
      map: [
        "#######",
        "#S# G #",
        "# ### #",
        "# #   #",
        "# # # #",
        "#   # #",
        "#######",
      ],
      solution: [
        "down",
        "down",
        "down",
        "down",
        "right",
        "right",
        "up",
        "up",
        "right",
        "right",
        "up",
        "up",
        "left",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-09",
      map: [
        "#######",
        "#S#   #",
        "# # # #",
        "# # #G#",
        "# # # #",
        "#   # #",
        "#######",
      ],
      solution: [
        "down",
        "down",
        "down",
        "down",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
        "right",
        "right",
        "down",
        "down",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-10",
      map: [
        "#######",
        "#S#G  #",
        "# ### #",
        "#   # #",
        "### # #",
        "#     #",
        "#######",
      ],
      solution: [
        "down",
        "down",
        "right",
        "right",
        "down",
        "down",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
        "left",
        "left",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-11",
      map: [
        "#######",
        "#S# G #",
        "# ### #",
        "#   # #",
        "### # #",
        "#     #",
        "#######",
      ],
      solution: [
        "down",
        "down",
        "right",
        "right",
        "down",
        "down",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
        "left",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-12",
      map: [
        "#######",
        "#S  # #",
        "### # #",
        "#G# # #",
        "# # # #",
        "#     #",
        "#######",
      ],
      solution: [
        "right",
        "right",
        "down",
        "down",
        "down",
        "down",
        "left",
        "left",
        "up",
        "up",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-13",
      map: [
        "#########",
        "#S#     #",
        "# # ### #",
        "# #  G# #",
        "# ##### #",
        "#       #",
        "####### #",
        "#       #",
        "#########",
      ],
      solution: [
        "down",
        "down",
        "down",
        "down",
        "right",
        "right",
        "right",
        "right",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
        "left",
        "left",
        "left",
        "left",
        "down",
        "down",
        "right",
        "right",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-14",
      map: [
        "#########",
        "#S#     #",
        "# ### # #",
        "#   # # #",
        "### # # #",
        "#   # # #",
        "# ### #G#",
        "#     # #",
        "#########",
      ],
      solution: [
        "down",
        "down",
        "right",
        "right",
        "down",
        "down",
        "left",
        "left",
        "down",
        "down",
        "right",
        "right",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
        "up",
        "up",
        "right",
        "right",
        "down",
        "down",
        "down",
        "down",
        "down",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-15",
      map: [
        "#########",
        "#S#  G  #",
        "# # #####",
        "# #     #",
        "# # ### #",
        "# # #   #",
        "# ### # #",
        "#     # #",
        "#########",
      ],
      solution: [
        "down",
        "down",
        "down",
        "down",
        "down",
        "down",
        "right",
        "right",
        "right",
        "right",
        "up",
        "up",
        "right",
        "right",
        "up",
        "up",
        "left",
        "left",
        "left",
        "left",
        "up",
        "up",
        "right",
        "right",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-16",
      map: [
        "#########",
        "#S#     #",
        "# ### # #",
        "#     # #",
        "####### #",
        "#    G# #",
        "# ##### #",
        "#       #",
        "#########",
      ],
      solution: [
        "down",
        "down",
        "right",
        "right",
        "right",
        "right",
        "up",
        "up",
        "right",
        "right",
        "down",
        "down",
        "down",
        "down",
        "down",
        "down",
        "left",
        "left",
        "left",
        "left",
        "left",
        "left",
        "up",
        "up",
        "right",
        "right",
        "right",
        "right",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-17",
      map: [
        "#########",
        "#S  #   #",
        "### #G# #",
        "#   # # #",
        "# ##### #",
        "# #     #",
        "# # ### #",
        "#   #   #",
        "#########",
      ],
      solution: [
        "right",
        "right",
        "down",
        "down",
        "left",
        "left",
        "down",
        "down",
        "down",
        "down",
        "right",
        "right",
        "up",
        "up",
        "right",
        "right",
        "right",
        "right",
        "up",
        "up",
        "up",
        "up",
        "left",
        "left",
        "down",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
    {
      id: "maze-18",
      map: [
        "#########",
        "#S      #",
        "####### #",
        "#  G  # #",
        "# ##### #",
        "#   #   #",
        "# # # ###",
        "# #     #",
        "#########",
      ],
      solution: [
        "right",
        "right",
        "right",
        "right",
        "right",
        "right",
        "down",
        "down",
        "down",
        "down",
        "left",
        "left",
        "down",
        "down",
        "left",
        "left",
        "up",
        "up",
        "left",
        "left",
        "up",
        "up",
        "right",
        "right",
      ],
      instruction: "用方向按钮带小兔到达家门。遇到岔路可以回头，虚线表示提示。",
    },
  ];
});
