(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.ChessContent = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : window, function () {
  const PUZZLE_TIERS = {
    mate1: [
      {
        id: "mate1-scholars-finish",
        title: "学者杀收官",
        goalLabel: "一步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5", "Bc4", "Nc6", "Qh5", "Nf6"],
        solutionLine: [{ actor: "player", san: "Qxf7#" }],
        intro: "白方已摆出经典进攻形态，找到直接将死的一步。",
        difficulty: "easy",
        tags: ["opening", "f7-weakness", "queen-bishop-battery"],
        hints: ["观察黑方王翼最脆弱的起始格。", "白后和白象共同瞄准同一个点。", "直接吃掉 f7 兵并将死。"],
        baseScore: 220,
        parSeconds: 12,
      },
      {
        id: "mate1-fools-mate",
        title: "愚人将杀",
        goalLabel: "一步杀",
        sideToMove: "b",
        setupMoves: ["f3", "e5", "g4"],
        solutionLine: [{ actor: "player", san: "Qh4#" }],
        intro: "黑方抓住王翼暴露的机会，一步结束战斗。",
        difficulty: "easy",
        tags: ["opening-trap", "queen-mate", "weak-king"],
        hints: ["白王对角线出现了致命空档。", "黑后可以一步制造将死。", "后走到 h4 完成将杀。"],
        baseScore: 220,
        parSeconds: 10,
      },
      {
        id: "mate1-legal-finish",
        title: "Légal 陷阱终手",
        goalLabel: "一步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "d6", "Nc3", "Bg4", "h3", "Bh5", "Nxe5", "Bxd1", "Bxf7+", "Ke7"],
        solutionLine: [{ actor: "player", san: "Nd5#" }],
        intro: "经典组合的最后一击，找出唯一的将死着法。",
        difficulty: "medium",
        tags: ["tactic", "mate-net", "knight-fork-theme"],
        hints: ["黑王在 e7，退路非常有限。", "白马可以跳到一个带将的位置。", "马跳 d5 构成将杀网。"],
        baseScore: 280,
        parSeconds: 18,
      },
    ],
    mate2: [
      {
        id: "mate2-scholars-build",
        title: "学者杀两步版",
        goalLabel: "两步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5", "Bc4", "Nc6"],
        solutionLine: [
          { actor: "player", san: "Qh5" },
          { actor: "opponent", san: "Nf6" },
          { actor: "player", san: "Qxf7#" },
        ],
        intro: "按照教学线路制造威胁并完成将死。",
        difficulty: "easy",
        tags: ["opening", "battery", "f7-attack"],
        hints: ["第一步先把后投入攻击线路。", "黑方常见应手是 Nf6。", "第二步吃 f7 终结。"],
        baseScore: 280,
        parSeconds: 22,
      },
      {
        id: "mate2-black-fools-route",
        title: "黑方愚人将杀（两步）",
        goalLabel: "两步杀",
        sideToMove: "b",
        setupMoves: ["f3"],
        solutionLine: [
          { actor: "player", san: "e5" },
          { actor: "opponent", san: "g4" },
          { actor: "player", san: "Qh4#" },
        ],
        intro: "黑方先争夺中心，等待白方继续暴露王翼后完成将死。",
        difficulty: "easy",
        tags: ["opening-trap", "center", "queen-mate"],
        hints: ["先手不是直接将军，而是先补一个发展/争中步。", "等白方再走一步削弱王翼。", "最后后到 h4 将死。"],
        baseScore: 280,
        parSeconds: 20,
      },
      {
        id: "mate2-legal-build",
        title: "Légal 陷阱（二步收束）",
        goalLabel: "两步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "d6", "Nc3", "Bg4", "h3", "Bh5", "Nxe5", "Bxd1"],
        solutionLine: [
          { actor: "player", san: "Bxf7+" },
          { actor: "opponent", san: "Ke7" },
          { actor: "player", san: "Nd5#" },
        ],
        intro: "从弃后后的位置开始，完成经典连续先手与将死。",
        difficulty: "medium",
        tags: ["combination", "sacrifice", "forcing-line"],
        hints: ["关键是继续给将，而不是急着吃回后。", "白象先手打击黑王。", "再用白马跳入终结点。"],
        baseScore: 360,
        parSeconds: 28,
      },
    ],
    mate3: [
      {
        id: "mate3-legal-trap",
        title: "Légal 经典弃后陷阱",
        goalLabel: "三步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "d6", "Nc3", "Bg4", "h3", "Bh5"],
        solutionLine: [
          { actor: "player", san: "Nxe5" },
          { actor: "opponent", san: "Bxd1" },
          { actor: "player", san: "Bxf7+" },
          { actor: "opponent", san: "Ke7" },
          { actor: "player", san: "Nd5#" },
        ],
        intro: "经典战术主题：先手弃后，利用子力协同完成致命打击。",
        difficulty: "hard",
        tags: ["combination", "queen-sacrifice", "legal-mate"],
        hints: ["第一步看起来会丢后，但能换来连续先手。", "核心思路是强制黑王走到不安全格。", "最后由轻子完成将死，不依赖后。"],
        baseScore: 520,
        parSeconds: 45,
      },
      {
        id: "mate3-scholars-full",
        title: "学者杀完整三步",
        goalLabel: "三步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5"],
        solutionLine: [
          { actor: "player", san: "Bc4" },
          { actor: "opponent", san: "Nc6" },
          { actor: "player", san: "Qh5" },
          { actor: "opponent", san: "Nf6" },
          { actor: "player", san: "Qxf7#" },
        ],
        intro: "从更早阶段开始构建威胁，体验将军、发展与终结的衔接。",
        difficulty: "medium",
        tags: ["opening-trap", "development", "f7-attack"],
        hints: ["先把象发展到能瞄准 f7 的线路。", "后再加入进攻，形成双重威胁。", "等黑方自然发展后立即终结。"],
        baseScore: 420,
        parSeconds: 32,
      },
      {
        id: "mate3-legal-fuller",
        title: "Légal 陷阱（完整三步杀进攻方）",
        goalLabel: "三步杀",
        sideToMove: "w",
        setupMoves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "d6", "Nc3", "Bg4", "h3", "Bh5"],
        solutionLine: [
          { actor: "player", san: "Nxe5" },
          { actor: "opponent", san: "Bxd1" },
          { actor: "player", san: "Bxf7+" },
          { actor: "opponent", san: "Ke7" },
          { actor: "player", san: "Nd5#" },
        ],
        intro: "与同主题题目不同，本题更强调第一步的弃后决断与连续计算。",
        difficulty: "hard",
        tags: ["forcing-line", "calculation", "legal-mate"],
        hints: ["先算清黑方若贪后会发生什么。", "每一步都应当是先手。", "终局图形与 Légal 将杀一致。"],
        baseScore: 560,
        parSeconds: 55,
      },
    ],
  };

  const LESSONS = [
    {
      id: "legal-mate",
      title: "Légal's Mate（经典弃后将杀）",
      summary: "通过弃后诱导对手贪吃，随后用轻子配合完成将杀的经典组合。",
      section: "tactical-combination",
      players: "Légal vs Saint Brie (teaching line)",
      era: "18th century motif",
      tags: ["combination", "queen-sacrifice", "mate-pattern"],
      moves: [
        { san: "e4", note: "白方占据中心并打开王象与后。" },
        { san: "e5" },
        { san: "Nf3", note: "发展王马，继续施压 e5。" },
        { san: "Nc6" },
        { san: "Bc4", note: "瞄准 f7，形成潜在战术支点。" },
        { san: "d6" },
        { san: "Nc3" },
        { san: "Bg4", note: "黑方钉住马，但也给了白方战术素材。" },
        { san: "h3" },
        { san: "Bh5" },
        { san: "Nxe5", note: "关键一击：表面上白后要被吃，实则是组合开始。" },
        { san: "Bxd1" },
        { san: "Bxf7+", note: "白方用象和马形成连续先手。" },
        { san: "Ke7" },
        { san: "Nd5#", note: "终结：马、象与王位受限共同构成将杀网。" },
      ],
    },
    {
      id: "scholars-mate",
      title: "Scholar's Mate（学者杀）",
      summary: "最经典的新手战术教学之一：快速发展并集中攻击 f7 弱点。",
      section: "opening-attack",
      players: "Classical teaching motif",
      era: "Foundational opening pattern",
      tags: ["opening-trap", "f7", "beginner-pattern"],
      moves: [
        { san: "e4", note: "白方打开后与象，争夺中心。" },
        { san: "e5" },
        { san: "Bc4", note: "白方的象直接瞄准 f7。" },
        { san: "Nc6" },
        { san: "Qh5", note: "后加入攻击，形成对 f7 的双重威胁。" },
        { san: "Nf6", note: "黑方发展马，但忽视了 f7 的致命点。" },
        { san: "Qxf7#", note: "白后吃兵将死，黑王无处可逃。" },
      ],
    },
    {
      id: "opera-game",
      title: "Morphy Opera Game（节选终局组合）",
      summary: "展现快速发展、弃子打开线路与重子协同压制的经典范例。",
      section: "initiative-attack",
      players: "Paul Morphy vs Duke Karl / Count Isouard",
      era: "1858",
      tags: ["initiative", "development", "sacrifice", "attack"],
      moves: [
        { san: "e4", note: "Morphy 以开放局开局，强调先手与发展。" },
        { san: "e5" },
        { san: "Nf3" },
        { san: "d6" },
        { san: "d4", note: "直接挑战中心，争取主动。" },
        { san: "Bg4" },
        { san: "dxe5" },
        { san: "Bxf3" },
        { san: "Qxf3" },
        { san: "dxe5" },
        { san: "Bc4" },
        { san: "Nf6" },
        { san: "Qb3", note: "同时盯住 b7 与 f7，制造双重压力。" },
        { san: "Qe7" },
        { san: "Nc3" },
        { san: "c6" },
        { san: "Bg5" },
        { san: "b5" },
        { san: "Nxb5", note: "开始战术突破，优先考虑王安全与线路。" },
        { san: "cxb5" },
        { san: "Bxb5+" },
        { san: "Nbd7" },
        { san: "O-O-O", note: "完成发展并把车快速投入 d 线。" },
        { san: "Rd8" },
        { san: "Rxd7", note: "典型交换牺牲，清除关键防守者。" },
        { san: "Rxd7" },
        { san: "Rd1" },
        { san: "Qe6" },
        { san: "Bxd7+", note: "继续抽走防守子，让黑王彻底裸露。" },
        { san: "Nxd7" },
        { san: "Qb8+" },
        { san: "Nxb8" },
        { san: "Rd8#", note: "所有子力协调到位，完成经典将杀。" },
      ],
    },
    {
      id: "capablanca-fragment",
      title: "Capablanca 风格：位置优势积累（教学片段）",
      summary: "通过稳健发展与结构控制逐步扩大优势，体现卡帕布兰卡的简洁风格。",
      section: "positional-play",
      players: "Capablanca style teaching fragment",
      era: "20th century positional school",
      tags: ["positional", "development", "space", "prophylaxis"],
      moves: [
        { san: "e4", note: "以开放局开始，争夺中心。" },
        { san: "e5" },
        { san: "Nf3", note: "自然发展并攻击 e5。" },
        { san: "Nc6" },
        { san: "Bb5", note: "西班牙开局：对白方长期位置压力非常典型。" },
        { san: "a6" },
        { san: "Ba4" },
        { san: "Nf6" },
        { san: "O-O", note: "先完成王安全，再考虑中心与兵结构。" },
        { san: "Be7" },
        { san: "Re1" },
        { san: "b5" },
        { san: "Bb3" },
        { san: "d6" },
        { san: "c3", note: "为 d4 做准备，稳步扩张中心控制。" },
        { san: "O-O" },
        { san: "h3", note: "限制对方轻子活跃格，体现预防性思维。" },
      ],
    },
    {
      id: "fischer-fragment",
      title: "Fischer 风格：王翼进攻构型（教学片段）",
      summary: "展示费舍尔式的协调发展与进攻构型搭建，强调先手与空间。",
      section: "opening-attack",
      players: "Fischer style teaching fragment",
      era: "20th century attacking school",
      tags: ["attack", "kingside", "development", "initiative"],
      moves: [
        { san: "Nf3", note: "灵活起手，保留中心兵推进时机。" },
        { san: "d5" },
        { san: "g3", note: "准备王翼象飞到长对角线。" },
        { san: "c5" },
        { san: "Bg2" },
        { san: "Nc6" },
        { san: "O-O", note: "先完成王翼安全，再组织中心与重子。" },
        { san: "e5" },
        { san: "d3" },
        { san: "Nf6" },
        { san: "e4", note: "中心发力，形成更清晰的主动计划。" },
        { san: "Be7" },
        { san: "Nbd2" },
        { san: "O-O" },
        { san: "Re1", note: "重子入中路，随时准备 e 线或王翼行动。" },
      ],
    },
    {
      id: "kasparov-fragment",
      title: "Kasparov 风格：主动性与空间推进（教学片段）",
      summary: "体现卡斯帕罗夫风格中的先手、空间与兵翼推进，为后续攻势做准备。",
      section: "initiative-attack",
      players: "Kasparov style teaching fragment",
      era: "Late 20th century dynamic chess",
      tags: ["initiative", "space", "kings-indian", "attack-preparation"],
      moves: [
        { san: "d4", note: "稳健争中心，为后续空间优势打基础。" },
        { san: "Nf6" },
        { san: "c4" },
        { san: "g6" },
        { san: "Nc3", note: "快速发展并支持中心兵。" },
        { san: "Bg7" },
        { san: "e4" },
        { san: "d6" },
        { san: "Nf3" },
        { san: "O-O" },
        { san: "Be2", note: "完成发展，避免过早暴露战术弱点。" },
        { san: "e5" },
        { san: "O-O" },
        { san: "Nc6" },
        { san: "d5", note: "抢占空间并限制黑方子力活动。" },
        { san: "Ne7" },
        { san: "b4", note: "兵翼推进扩展战场，体现主动性压制思路。" },
      ],
    },
  ];

  return {
    PUZZLE_TIERS,
    LESSONS,
  };
});
